const { constants: HTTP_STATUS } = require('http2');

const STATUS_OK = HTTP_STATUS.HTTP_STATUS_OK;
const STATUS_CREATED = HTTP_STATUS.HTTP_STATUS_CREATED;
const STATUS_BAD_REQUEST = HTTP_STATUS.HTTP_STATUS_BAD_REQUEST;
const STATUS_UNAUTHORIZED = HTTP_STATUS.HTTP_STATUS_UNAUTHORIZED;
const STATUS_FORBIDDEN = HTTP_STATUS.HTTP_STATUS_FORBIDDEN;
const STATUS_NOT_FOUND = HTTP_STATUS.HTTP_STATUS_NOT_FOUND;
const STATUS_CONFLICT = HTTP_STATUS.HTTP_STATUS_CONFLICT;
const STATUS_INTERNAL_SERVER_ERROR = HTTP_STATUS.HTTP_STATUS_INTERNAL_SERVER_ERROR;
const MONGO_DUPLICATE_ERROR = 11000;

module.exports = {
  STATUS_OK,
  STATUS_CREATED,
  STATUS_BAD_REQUEST,
  STATUS_UNAUTHORIZED,
  STATUS_FORBIDDEN,
  STATUS_NOT_FOUND,
  STATUS_CONFLICT,
  STATUS_INTERNAL_SERVER_ERROR,
  MONGO_DUPLICATE_ERROR,
};

// '200': 'OK',
// '201': 'Created',
// '400': 'Bad Request',
// '401': 'Unauthorized',
// '403': 'Forbidden',
// '404': 'Not Found',
// '409': 'Conflict',
// '500': 'Internal Server Error',
